services:
  frontend:
    build:
      context: ./Blog.UI
      dockerfile: Dockerfile
    container_name: vue-frontend
    ports:
      - "5173:5173"
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Blog.API/Dockerfile
    container_name: blog-api
    ports:
      - "5058:5058"